config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  resources :games do    
    resources :guides
    resources :resources
  end

  resources :votes

  resources :requests
  #resources :votes


  resources :users do     
    resources :guides
    resources :comments
    resources :posts    
  end

  resources :guides do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :resources do
    resources :comments
  end



  



  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/votes/new', to: 'votes#new'
  get '/games/:id/requests', to: 'games#requests', as: 'game_requests'

end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :game
	belongs_to :user
	has_many :comments
  has_many :votes
  
	def count_votes(type)
    votes.where(vote_type: type).count
  end

  #compares "up" votes and "down" votes
  def score
    votes.where(vote_type: "up").count -
    votes.where(vote_type: "down").count
  end

  def voted_up?(user)
    if votes.where(user_id: user.id).where(vote_type:"up").where(request_id:id).count >= 1
      return true
    else
      return false
    end
  end

  def voted_down?(user)
    if votes.where(user_id: user.id).where(vote_type:"down").where(request_id:id).count >= 1
      return true
    else
      return false
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

	before_action :set_request, only: [:edit, :update, :destroy]
	before_action :set_game, only: [:edit, :update, :destroy]
	#authorize_resource

	def index
		@requests = Request.all		
	end

	def show
		@request = Request.find(params[:id])
		@game = Game.find(@request.game_id)
	end

	def new
		@request = Request.new			
		@request.answered = false
		@game = Game.select('id, name')
	end

	def edit
	end

	def create		
		@request = Request.new(request_params)
		current_user.requests.new(request_params)	
		@request.user_id = current_user.id
		@request.status = "Not being worked on"
		@request.score = 0		
		
		respond_to do |format|
			if @request.save				
				format.html{redirect_to @request, notice: 'Request was successfully created.'}
			else
				flash[:error] = "Request not created."
				format.html{render :new}
			end
		end		
	end

	def update
		respond_to do |format|
			if @request.update(request_params)
				format.html {redirect_to game_request_path(@game, @request), notice: "Request was successfully updated."}
			else
				format.html{render :edit}
			end
		end
	end	

	def destroy
		@request.destroy
		respond_to do |format|
			format.html {redirect_to root_path, notice: "Request was succesfully removed."}
		end
	end

	private
		def set_request
			@request = Request.find(params[:id])
		end

		def set_game
			@game = @request.game 	
		end

		def request_params
			params.require(:request).permit(:title, :body, :game_id)
		end
end

app/views/requests/_form.html.haml
= form_for (@request) do |f|
  = f.label :title
  = f.text_field :title
  %br

  = f.label :body
  = f.text_field :body
  %br
  = f.label :game_id
  = f.select :game_id, options_for_select(@game.map {|r| [r.name, r.id]})
  = f.submit "Create Request"

app/views/requests/index.html.haml
%h2
  Requests:
%table{class:"list", id:"index_requests"}
  %thead
    %tr
      -if can? :delete, request
        %td
          %strong
            Delete:
      -if can? :vote, request
        %td
          %strong
            Vote:      
      %td
        %strong
          Score:
      %td
        %strong
          Status:
      %td
        %strong
          Title:
    %tr
      %td
        %br
  -@requests.each do |request|
    %tbody        
      %tr
        -if can? :delete, request        
          %td
            =link_to "Delete", request, method: :delete, data: {confirm: "Are you sure?"}
        -if can? :vote, request
          %td
            = link_to "Vote", new_vote_path
        %td
          = (request.count_votes("up") - request.count_votes("down"))

        %td
          =request.status
        %td
          =link_to request.title, request
    %tbody      
      %tr
        %td
          %br   

%h6
  =link_to "New Request", new_request_path
      
      

      

app/views/requests/new.html.haml
%h1 New Request

= render 'form'

app/views/requests/show.html.haml
%p
  Request for:
  =link_to @game.name, @game
%table
  %thead
    %tr
      %td
        Score:
      %td
        Title:         
      %td
        Status:
      %td
        Author:
  %tbody
    %tr
      %td
        =@request.count_votes("up") - @request.count_votes("down")
      %td
        =@request.title
         
      %td
        =@request.status
      %td
        =link_to @request.user.name, @request.user
  %tbody
    %tr
      %td
        %br
    %tr
      %td
        =@request.body
-if can? :delete, @request
  =link_to "Delete this request", @request, method: :delete, data:{confirm:"Are you sure?"}
  %br