config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  resources :games do    
    resources :guides
    resources :resources
  end

  resources :votes

  resources :requests
  #resources :votes


  resources :users do     
    resources :guides
    resources :comments
    resources :posts    
  end

  resources :guides do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :resources do
    resources :comments
  end



  



  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/votes/new', to: 'votes#new'
  get '/games/:id/requests', to: 'games#requests', as: 'game_requests'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :requests
	has_many :guides
	has_many :resources
	has_many :requests

  has_many :users, through: :requests

	belongs_to :user
	
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	before_action :set_game, only: [:show, :edit, :update, :destroy]

	def new
		@game = Game.new
	end

	def create
		@game = Game.new(game_params)

		respond_to do |format|
			if @game.save
				flash[:success] = "Game was successfully created."
				format.html {redirect_to @game}
			else
				flash[:error] = "There was an error. Game not created."
				format.html {render :new}
			end
		end
	end

	def requests
		#new vote
		@vote = Vote.new
		@game = Game.find(params[:id])
		@requests = @game.requests
		@requests = @requests.sort_by{|a| -a.score}
	end	

	def edit
		@game = Game.find(params[:id])
	end

	def show
	end

	def update
		respond_to do |format|
			if @game.update(game_params)
				flash[:success] = "Game successfully updated."
				format.html{redirect_to @game}
			else
				flash[:error] = "Game not successfully updated."
				format.html{render :edit}
			end
		end
	end

	def destroy
		@game.guides.destroy
		@game.resources.destroy
		@game.requests.destroy

		@game.destroy
		respond_to do |format|
			flash[:success] = "Game successfully destroyed."
			format.html {redirect_to root_path}
		end		
	end
	
	private
		def set_game
			@game = Game.find(params[:id])
		end

		def game_params
			params.require(:game).permit(:name, :description)
		end
end

app/views/games/_form.html.haml
= form_for(@game) do |f|
	= f.label :name
	= f.text_field :name

	%br

	= f.label :description
	= f.text_field :description

	%br

	= f.submit "Create game"

app/views/games/edit.html.haml
%h1 Editing Game
=form_for(@game) do |f|
  =f.label :name
  =f.text_field :name

  %br

  =f.label :description
  =f.text_field :description

  %br

  =f.submit "Update"

app/views/games/new.html.haml
= render 'form'

app/views/games/requests.html.haml
%p
  Request for:
  =link_to @game.name, @game
%table{class:"list", id:"index_game_requests"}
  %thead
    %tr
      -if can? :vote, request
        %td
          
      %td
        Score:
      %td
        Title:
         
      %td
        Status:
      %td
        Author:
  %div{id:"requests_table"}
  -@requests.each do |request|

    -if request.voted_up?(current_user)
      - up_suffix = "_clicked"
    -elsif request.voted_down?(current_user)
      - down_suffix = "_clicked"
    -else
      -up_suffix = ""
    %tbody
      %tr
        %td          
          =form_for @vote, html:{class:"request_vote"}, remote: true do |f| 
            =f.hidden_field :request_id, :value => request.id
            =f.hidden_field :user_id, :value => current_user.id 
            =f.hidden_field :vote_type, :value => "up"
            =f.submit "^", html:{class:"up_submit", class:"upvote#{up_suffix}"}
                   
          =form_for @vote, html:{class:"request_vote"}, remote: true do |f| 
            =f.hidden_field :request_id, :value => request.id
            =f.hidden_field :user_id, :value => current_user.id 
            =f.hidden_field :vote_type, :value => "down"
            =f.submit "v", html:{class:"down_submit", class:"downvote#{down_suffix}"}
                        
        %td
          %div{class:"score", id:"game_request_#{request.id}_score"}
            =request.score
        %td
          =request.title           
        %td
          =request.status
        %td
          =link_to request.user.name, request.user      
        %td
          -if can? :delete, request
            =link_to "Delete this request", request, method: :delete, data:{confirm:"Are you sure?"}
            %br    
      
      

app/views/games/requests.js.erb
$('#game_request_<%= request.id %>_score').html(<%=request.score%>)
$('.request_vote')[0].reset();

app/views/games/show.html.haml
-if can? :edit, @game
	%br
	=link_to "Edit Game", edit_game_path(@game)
-if can? :destroy, @game	
	%br
	=link_to "Delete Game", @game, method: :delete, data:{confirm:"Are you sure? All guides, requests, and resources belonging to game will be destroyed."}
%table{class:"list", id:"show_game"}
	%thead
		%tr
			%th Game Name
			%th Game Description
	%tbody
		%tr
			%td 
				=@game.name
			%td 
				=@game.description
%table{class:"list", id:"game_links"}
	%thead
		%tr
			%th
				=link_to "Requests", game_requests_path(@game)
			%th
				=link_to "Guides", game_guides_path(@game)
			%th
				=link_to "Resources", game_resources_path(@game)
		%tr
			%td				
				=link_to "New Request", new_request_path
			%td				
				=link_to "New Guide", new_game_guide_path(@game.id)
			%td				
				=link_to "New Resource", new_game_resource_path(@game.id)
				