config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  resources :games do    
    resources :guides
    resources :resources
  end

  resources :votes

  resources :requests
  #resources :votes


  resources :users do     
    resources :guides
    resources :comments
    resources :posts    
  end

  resources :guides do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :resources do
    resources :comments
  end



  



  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/votes/new', to: 'votes#new'
  get '/games/:id/requests', to: 'games#requests', as: 'game_requests'

end

app/views/layouts/_footer.html.haml
= link_to "Home", root_path

app/views/layouts/_header.html.haml
=render 'shared/error_messages'
-flash.each do |name, msg|
	=content_tag :div, msg, class: name

-if signed_in? 
	SIGNED IN AS:
	=link_to current_user.name, current_user
	=link_to "Sign Out", signout_path, method: :delete

-else
	=link_to "Sign Up", signup_path
	=link_to "Sign In", signin_path



=link_to "Add Game", new_game_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoardGameGuides</title>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>


</head>
<body>
<%= render 'layouts/header' %> 
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>